### PR TITLE
Fixing URL issues in ReadMe

### PR DESCRIPTION
**Pull request by elamaran11**
This PR is to fix incorrect URL in ReadMe for `gitea` and `argocd` repo.

### CODE REVIEW

**Comment by cmoulliard** [comment]
The ingress addresses to access: gitea and argocd are respectively:
```
[snowdrop@charles-vm ~]$ k get ingress -A
NAMESPACE   NAME                     CLASS   HOSTS                                 ADDRESS     PORTS   AGE
argocd      argocd-server-ingress    nginx   argocd.cnoe.localtest.me              localhost   80      4h31m
gitea       my-gitea                 nginx   gitea.cnoe.localtest.me               localhost   80      4h31m
```
So I don t really understand why you are changing them into: `cnoe.localtest.me:8443/gitea/...` and `cnoe.localtest.me:8443/argocd/...`

**Comment by elamaran11** [comment]
> The ingress addresses to access: gitea and argocd are respectively:
> 
> ```
> [snowdrop@charles-vm ~]$ k get ingress -A
> NAMESPACE   NAME                     CLASS   HOSTS                                 ADDRESS     PORTS   AGE
> argocd      argocd-server-ingress    nginx   argocd.cnoe.localtest.me              localhost   80      4h31m
> gitea       my-gitea                 nginx   gitea.cnoe.localtest.me               localhost   80      4h31m
> ```
> 
> So I don t really understand why you are changing them into: `cnoe.localtest.me:8443/gitea/...` and `cnoe.localtest.me:8443/argocd/...`

We are not changing the Ingress but the URL isnt correct.

**Comment by cmoulliard** [comment]
> We are not changing the Ingress but the URL isnt correct.

The URLs to be used are:
```
https://gitea.cnoe.localtest.me:8443/
https://argocd.cnoe.localtest.me:8443
```

**Comment by elamaran11** [comment]
> > We are not changing the Ingress but the URL isnt correct.
> 
> The URLs to be used are:
> 
> ```
> https://gitea.cnoe.localtest.me:8443/
> https://argocd.cnoe.localtest.me:8443
> ```

The URLs that work for me with latest version and setup are :

```
https://cnoe.localtest.me:8443/argocd
https://cnoe.localtest.me:8443/gitea
```

**Pull request closed without merging**
