### PR TITLE
Backstage Integrations Upgrade for Terraform with TOFU - Doc Updates

### PR DESCRIPTION
**Pull request by elamaran11**
Backstage Integrations Upgrade for Terraform with TOFU - Doc Updates

### CODE REVIEW

**Comment by elamaran11** [comment]
@nabuskey @nimakaviani Im just updating the doc, do you know what this error is about?

**Comment by nabuskey** [comment]
Don't worry about the error. It's related to a bug in tests where execution order is not guaranteed. It's fixed in #255.

**Review by nabuskey — APPROVED** [review]
LGTM

**Comment by elamaran11** [comment]
> Don't worry about the error. It's related to a bug in tests where execution order is not guaranteed. It's fixed in #255.

Cool thanks.

**Pull request merged**
