### PR TITLE
add feature GH template

### PR DESCRIPTION
**Pull request by nabuskey**
Related to  #62

### CODE REVIEW

**Review by nimakaviani — APPROVED** [review]
LGTM

**Comment by omrishiv** [comment]
Would anyone mind if I mived this to cnoe-io/.github?

**Comment by nabuskey** [comment]
> Would anyone mind if I moved this to cnoe-io/.github?

Nope. As long as templates are used for feature requests. I think this one is generic enough that we can reuse.

**Comment by omrishiv** [comment]
https://github.com/cnoe-io/.github/pull/2

**Pull request merged**
