### PR TITLE
PR to fix the issues reported by the Issue 28

### PR DESCRIPTION
**Pull request by cmoulliard**
- PR to fix the issues reported by the Issue #28

### CODE REVIEW

**Comment by cmoulliard** [comment]
kind cluster config comparison is failing part of the cluster_test.go test as additional chars are included such as: `\"`, '\t',  `  ` are added - see here: https://gist.github.com/cmoulliard/53fb4cfb0c40c3041469b70477f1562c#file-gistfile1-txt-L35-L82. I can reproduce the issue locally but I don't know if this is a go issue with diff, OS, etc

**Comment by cmoulliard** [comment]
Proposition to use testcontainer: #49 
WDYT ? @nabuskey

**Comment by cmoulliard** [comment]
Is a docker registry created OOTB when we execute `make test` part of a github workflow ? 
The `kind` network should be added to /etc/hosts or registered as docker network otherwise `registry_test.go:31: Error reconciling registry: Error response from daemon: network kind not found` will continue to fail 
@nabuskey

**Comment by nabuskey** [comment]
> Is a docker registry created OOTB when we execute `make test` part of a github workflow ?

Yeah docker is one of tools that's included in the Ubuntu image that GitHub provides. 

I think I want to hold off on moving to test containers, if we use Gitea like you suggested, we don't need to build images.

**Comment by cmoulliard** [comment]
> I think I want to hold off on moving to test containers, if we use Gitea like you suggested, we don't need to build images.

I agree with you. Nevertheless, if it is need to bump a container during some tests execution, using TestContainer will simplify our life

**Comment by cmoulliard** [comment]
As most of the issues have been fixed, I propose to close this PR. WDYT ? @nabuskey

**Comment by nabuskey** [comment]
Yeah let's close this and thanks for working on this.  I do like your approach with TestContainers though. If a need arises for something like this, we should definitely consider it.

**Pull request closed without merging**
