### PR TITLE
Update readme, removing WIP and adding install info

### PR DESCRIPTION
**Pull request by greghaynes**
Lets remove the WIP notice at the top of the readme, we're at a high enough level of maturity this is likely causing more harm than good.

Also adding some commands to make it extremely simple for a new user to get up and running.

### CODE REVIEW

**Comment by nabuskey** [comment]
Thanks for this! Removing the WIP notice is something I wanted to talk about during the next community meeting. I am 100% ok with removing it considering it is being used at AWS workshops with success and featured in conference talks.

**Comment by cmoulliard** [comment]
The project and tool is not anymore WIP ;-)

**Comment by greghaynes** [comment]
@nabuskey Do you want to approve this here or are you wanting to wait for some discussion on it? It seems we're all onboard with this no longer being WIP so I'd lean toward just merging this, but up to you!

**Review by nabuskey — APPROVED** [review]
Just wanted give people some time to voice their opinions. I'm all for this.

**Pull request merged**
