### PR TITLE
fix gitea registry for path based routing

### PR DESCRIPTION
**Pull request by nabuskey**
fixes: #410 
fixes: #344

### CODE REVIEW

**Review by cmoulliard — COMMENTED** [review]
The name of the parameter that we are using here: `use-path-routing` is not meaningful as in fact it allows the user to configure the internal container registry using either the FQDN of gitea or the domain name.

I suggest to rename it to something like `no-fqdn`

By the way, the documentation should be reviewed to detail what `idp` do when this parameter/Argument is selected !!

**Comment by nabuskey** [comment]
> The name of the parameter that we are using here: `use-path-routing` is not meaningful as in fact it allows the user to configure the internal container registry using either the FQDN of gitea or the domain name.
> 
> I suggest to rename it to something like `no-fqdn`
> 
> By the way, the documentation should be reviewed to detail what `idp` do when this parameter/Argument is selected !!

We can revisit the flag name in the future for sure. We do need to illustrate what the flag does too.

**Review by blakeromano — APPROVED** [review]
I do think before we release we need some protection on if cluster was created with path based routing and I create with host based routing on the second run that we should log an error or some sort of indication that hey we are doing something wrong or this requires to be recreated... 

Talking with Manabu on slack I think we are in agreement that as long as both this and that are in the same release I am fine with approving this

**Comment by nabuskey** [comment]
Opened https://github.com/cnoe-io/idpbuilder/issues/416 to track what Blake said.

**Pull request merged**
