### PR TITLE
Plugin scaffolder actions

### PR DESCRIPTION
**Pull request by jessesanford**

### CODE REVIEW

**Comment by jessesanford** [comment]
@nabuskey I want to get the conversation started on getting the fixes for enabling plugin-scaffolder-actions merged.

**Comment by jessesanford** [comment]
FYI the image is built from the k8s-apply branch on the backstage-app... I have collapsed all the commits from that branch into a commit on a new plugin-scaffolder-actions branch on that repo and created this PR so that it's easier to review: https://github.com/cnoe-io/backstage-app/pull/15/files

**Comment by cmoulliard** [comment]
Can you please add a description or at least an issue describing the purpose of this PR ? @jessesanford

**Comment by cmoulliard** [comment]
If idpbuilder installs a specific packaging of backstage, then our README file should mention it to keep the user informed. This is what I do in our project by example: https://github.com/q-shift/backstage-playground?tab=readme-ov-file#backstage-qshift-showcase @jessesanford

**Comment by nabuskey** [comment]
Closing this since we moved our examples to the stacks repo. Please reopen in that repo if this is still relevant.

**Pull request closed without merging**
