### PR TITLE
chore: rename buildName flag to name

### PR DESCRIPTION
**Pull request by xoanmm**
Solves issue #65

### CODE REVIEW

**Comment by nabuskey** [comment]
> I wonder whether we should keep both flags for now with buildName called out as deprecated, and we remove it in a v0.6.0 release? dont want to break people, in case anyone is using it in a CI or something.

Agree with this. The issue was written when we didn't have to worry about backward compatibility just yet. 

Thanks for this PR and would love to merge it once the flag is preserved.

**Comment by xoanmm** [comment]
@nabuskey @nimakaviani so you suggest to modify the actual PR with both flags to keep backward compatibility showing a message like `deprecated, will be removed in future versions use name` in `buildName` flag?

**Comment by nabuskey** [comment]
> @nabuskey @nimakaviani so you suggest to modify the actual PR with both flags to keep backward compatibility showing a message like `deprecated, will be removed in future versions use name` in `buildName` flag?

Yep. It should accept either one, `name` or `build-name`.  If `build-name` is used, print out a message like you said, then continue. Something like `--build-name flag is deprecated and will be removed in a future release. Please use --name instead.`

**Comment by nabuskey** [comment]
Closing this due to inactivity. Feel free to reopen.

**Comment by cmoulliard** [comment]
> Closing this due to inactivity. Feel free to reopen.

I will submit a PR soon ;-)

**Comment by cmoulliard** [comment]
Done through a different PR

**Pull request closed without merging**
