### PR TITLE
Do not allocate memory for system in kind

### LINKED ISSUE #197: [Bug]: system-reserved memory too high
### What is your environment, configuration, and command?

Using latest idpbuilder with `examples/ref-implementation`
Running on Linux EC2 c5.large (4CPUs, 8GB)

### What did you do and What did you see instead?

The kind cluster is created a too high `system-reserved` in the default configuration.
It leads to unstable stack and a lot of containers OOMKilled
```
vscode ➜ ~/idpbuilder (main) $ kubectl get pods --all-namespaces -o go-template='{{range .items}}{{range .status.containerStatuses}}{{if .lastState.terminated}}{{if eq .lastState.terminated.reason "OOMKilled"}}{{$pod := index .containerID}}{{printf "%s\t%s\t%s\t%s\n" $pod .name .lastState.terminated.reason .lastState.terminated.finishedAt}}{{end}}{{end}}{{end}}{{end}}'
containerd://e4833221afec3fd7a4c83a5d9724e86ba8c9f552e2b445ad30c55fc513edbfc0   argocd-application-controller   OOMKilled       2024-04-22T00:01:26Z
containerd://b2af2e2d817bfd1c5fe51b6c1a185c6ef290f0c08164870474379c342012ccfd   argocd-repo-server      OOMKilled       2024-04-21T23:56:42Z
containerd://33a584b80d5427eb8aee6ec5bfa17701954eb56e28e55c3f4b2da5f55d9c13b4   argocd-server   OOMKilled       2024-04-21T23:59:30Z
containerd://1fa47ea3ef4ad6086aa69c065d74b977f84357f6e8bef3d3e9806659fa59dc69   crossplane      OOMKilled       2024-04-21T23:59:47Z
containerd://519f3c0bfc07afe15c2dc5dc3fe5651a5adad918c5ee3173be408e3f0f80dff8   external-secrets        OOMKilled       2024-04-21T23:56:44Z
containerd://03c0177bf4b3350e1c5e3bdebda310d8631ad2279e1c4469e39411a8cd7acbb6   cert-controller OOMKilled       2024-04-21T23:59:37Z
containerd://913ff894f2b17c8b6c4acb4e7004658a41c780dd46763a2c980c19685b17baef   gitea   OOMKilled       2024-04-22T00:01:38Z
```

### Additional Information. Logs.

```shell
We should remove the `system-reserved` from the kind configuration, having a value of `4Gi` is for system processes like sshd, udev, leaves too little memory left for pods.
I proposed we don't pass this flag. If the user has a use case where system-reserved needs to be high or specify in kind, they can pass a custom config with `--kind-config` flag
```

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #197

### CODE REVIEW

**Comment by nabuskey** [comment]
I actually don't know why these were in place. We can certainly reserve memory for system resources but 4G does seem too much. @greghaynes Any consequences for reducing these?

**Comment by csantanapr** [comment]
Can we get an update on this PR? 
Some users can benefit of been able to run idpbuilder in systems with lower memory than 12GB of RAM

**Comment by greghaynes** [comment]
I dont think this was intentional - I'm pretty sure this came in when we copied an example configuration.

**Comment by greghaynes** [comment]
@csantanapr did you intentionally close this? Removing this memory requirement seems reasonable to me.

**Comment by nimakaviani** [comment]
re-opening. i think closing this was accidental.

**Review by nabuskey — APPROVED** [review]

**Pull request merged**
